version: '3'
services:
  fastapi:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    image: fastapi-image
    container_name: fastapi-container

  nginx:
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    image: nginx-image
    container_name: nginx-container
    ports:
      - "80"
    depends_on:
      - fastapi
    links:
      - fastapi