version: '3'
services:
  fastapi:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    image: fastapi-image
    container_name: fastapi-container

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    image: nginx-image
    container_name: nginx-container
    ports:
      - "80"
    depends_on:
      - fastapi
    links:
      - fastapi