version: '3'
services:
  fastapi:
    build:
      context: ./backend
      dockerfile: dockerfile
    network_mode: host
    image: fastapi-image
    container_name: fastapi-container

  nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile
    network_mode: host
    image: nginx-image
    container_name: nginx-container
    volumes: ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - fastapi